version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tailnet
    main: ./cmd/tailnet
    binary: tailnet
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitCommit={{.ShortCommit}} -X main.buildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: tailnet
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz, zip]
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "ghcr.io/sudosu404/tailnet-cli:{{ .Tag }}-amd64"
      - "ghcr.io/sudosu404/tailnet-cli:latest-amd64"
      - "ghcr.io/sudosu404/tailnet-cli:v{{ .Major }}.{{ .Minor }}-amd64"
      # TODO: Uncomment for 1.0.0 release
      # - "ghcr.io/sudosu404/tailnet-cli:{{ .Major }}-amd64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    skip_push: "{{ if .IsSnapshot }}true{{ else }}false{{ end }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Tailscale-based reverse proxy manager"
      - "--label=org.opencontainers.image.url=https://github.com/sudosu404/tailnet-cli"
      - "--label=org.opencontainers.image.source=https://github.com/sudosu404/tailnet-cli"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates:
      - "ghcr.io/sudosu404/tailnet-cli:{{ .Tag }}-arm64"
      - "ghcr.io/sudosu404/tailnet-cli:latest-arm64"
      - "ghcr.io/sudosu404/tailnet-cli:v{{ .Major }}.{{ .Minor }}-arm64"
      # TODO: Uncomment for 1.0.0 release
      # - "ghcr.io/sudosu404/tailnet-cli:{{ .Major }}-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    use: buildx
    skip_push: "{{ if .IsSnapshot }}true{{ else }}false{{ end }}"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Tailscale-based reverse proxy manager"
      - "--label=org.opencontainers.image.url=https://github.com/sudosu404/tailnet-cli"
      - "--label=org.opencontainers.image.source=https://github.com/sudosu404/tailnet-cli"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "ghcr.io/sudosu404/tailnet-cli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/sudosu404/tailnet-cli:{{ .Tag }}-amd64"
      - "ghcr.io/sudosu404/tailnet-cli:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/sudosu404/tailnet-cli:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/sudosu404/tailnet-cli:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/sudosu404/tailnet-cli:v{{ .Major }}.{{ .Minor }}-arm64"
  # TODO: Uncomment for 1.0.0 release
  # - name_template: "ghcr.io/sudosu404/tailnet-cli:{{ .Major }}"
  #   image_templates:
  #     - "ghcr.io/sudosu404/tailnet-cli:{{ .Major }}-amd64"
  #     - "ghcr.io/sudosu404/tailnet-cli:{{ .Major }}-arm64"
  - name_template: "ghcr.io/sudosu404/tailnet-cli:latest"
    image_templates:
      - "ghcr.io/sudosu404/tailnet-cli:latest-amd64"
      - "ghcr.io/sudosu404/tailnet-cli:latest-arm64"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: hector
    name: tailnet
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"