services:
  # Whoami service using traefik/whoami
  whoami:
    image: traefik/whoami:v1.10.3
    labels:
      # tailnet will automatically discover this container
      - "tailnet.enabled=true"
      - "tailnet.service.name=whoami"
      - "tailnet.service.port=80"
      - "tailnet.service.whois_enabled=true" # Add identity headers
    networks:
      - tailnet-network

volumes:
  db-data:

networks:
  tailnet-network:
    # Reference the external network created by tailnet-compose.yml
    external: true
    name: tailnet-shared-network
