services:
  # tailnet proxy with Docker label configuration
  tailnet:
    image: ghcr.io/sudosu404/tailnet-cli:latest
    command:
      - "--provider"
      - "docker"
      - "--verbose"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - tailnet-state:/var/lib/tailnet
    networks:
      - tailnet-demo
    labels:
      # Tailscale OAuth configuration
      - "tailnet.tailscale.oauth_client_id_env=TS_OAUTH_CLIENT_ID"
      - "tailnet.tailscale.oauth_client_secret_env=TS_OAUTH_CLIENT_SECRET"
      - "tailnet.tailscale.default_tags=tag:server,tag:proxy"
      - "tailnet.tailscale.state_dir=/var/lib/tailnet"

      # Global configuration
      - "tailnet.global.metrics_addr=:9090"
      - "tailnet.global.read_header_timeout=30s"
      - "tailnet.global.write_timeout=30s"
      - "tailnet.global.idle_timeout=120s"
      - "tailnet.global.access_log=true"
    environment:
      # Replace with your actual OAuth credentials
      # You can get these from: https://login.tailscale.com/admin/settings/oauth
      - TS_OAUTH_CLIENT_ID=${TS_OAUTH_CLIENT_ID}
      - TS_OAUTH_CLIENT_SECRET=${TS_OAUTH_CLIENT_SECRET}
    ports:
      - "9090:9090" # Metrics port

  # Backend API service with tailnet labels
  api-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - tailnet-demo
    environment:
      - SERVICE_NAME=api
      - PORT=8080
    labels:
      # Enable tailnet for this container
      - "tailnet.enabled=true"
      - "tailnet.service.name=api"
      - "tailnet.service.port=8080"
      - "tailnet.service.whois_enabled=true"
      - "tailnet.service.whois_timeout=1s"
      # Add custom headers
      - "tailnet.service.upstream_headers.X-Service-Type=api"
      - "tailnet.service.downstream_headers.X-Frame-Options=DENY"
    expose:
      - "8080"

  # Backend Web service with tailnet labels
  web-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - tailnet-demo
    environment:
      - SERVICE_NAME=web
      - PORT=8081
    labels:
      # Enable tailnet for this container
      - "tailnet.enabled=true"
      - "tailnet.service.name=web"
      - "tailnet.service.port=8081"
      - "tailnet.service.whois_enabled=true"
      # Custom timeouts for this service
      - "tailnet.service.read_header_timeout=60s"
      - "tailnet.service.write_timeout=60s"
      # Disable access logging for this service
      - "tailnet.service.access_log=false"
      # Security headers
      - "tailnet.service.downstream_headers.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      - "tailnet.service.downstream_headers.X-Content-Type-Options=nosniff"
      - "tailnet.service.remove_downstream=Server,X-Powered-By"

  # Admin service with Tailscale Funnel enabled
  admin-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    networks:
      - tailnet-demo
    environment:
      - SERVICE_NAME=admin
      - PORT=9000
    labels:
      # Enable tailnet for this container
      - "tailnet.enabled=true"
      - "tailnet.service.name=admin"
      - "tailnet.service.port=9000"
      - "tailnet.service.whois_enabled=true"
      #- "tailnet.service.funnel_enabled=true"  # Expose via Tailscale Funnel
      - "tailnet.service.ephemeral=false"

volumes:
  tailnet-state:
    driver: local

networks:
  tailnet-demo:
    driver: bridge
